name: Randomiconpaper
version: ${project.version}
main: randomiconpaper.randomiconpaper.RandomIconPaper
api-version: 1.16
authors: [ Elliot ]
load: STARTUP
description: Sets the server icon to a random Icon from a folder each ping
commands:
  ripreload:
    description: Reload rip icons
permissions:
  rip.reload:
    description: lets a player reload the config
    default: op