name: RandomIcon
version: ${project.version}
main: org.elliotnash.randomicon.spigot.SpigotMain
api-version: 1.16
load: STARTUP
authors: [ Elliot ]
description: Plugin to change the server icon to a different image each ping
website: elliotnash.org
