name: RandomIcon
version: ${jenkins.buildNumber}
website: https://ci.elliotnash.org/job/Minecraft/job/RandomIcon
main: org.elliotnash.randomicon.spigot.SpigotMain
api-version: 1.16
authors: [ Elliot ]
load: STARTUP
description: Sets the server icon to a random Icon from a folder each ping
commands:
  rireload:
    description: Reload rip icons
permissions:
  ri.reload:
    description: lets a player reload the config
    default: op